config/routes.rb
Rails.application.routes.draw do
  get "/", to: 'home#index'
  get 'member_creation', to: 'members#new'
  post 'member_creation', to: 'members#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
  # validates :eth_address, presence: true, uniqueness: true
  validates :eth_nonce, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    @member.eth_nonce = SecureRandom.uuid
    if @member.save
      redirect_to "/"
      flash[:notice] = "New account created for: #{@member.username}"
    else
      flash[:error] = "That username already exists!"
    end
  end

private
  def member_params
    params.require(:member).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/home/index.html.erb
<h1> Welcome to the Rails and Ethereum Wallet connection portal! </h1>

<h2> First, create an account with the link below to connect your Ethereum Wallet. </h2>

<%= link_to "Sign-Up", member_creation_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MetamaskRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/new.html.erb
<h1>Create your account</h1>

<%= form_for @member, url: member_creation_path do |form| %>
  <%= form.label "Username:" %>
  <%= form.text_field :username %> <br />
  <% form.text_field :eth_address, readonly: true, class: "eth_address" %> <br />
  <%= form.submit "Sign-up with Ethereum" %>
<% end %>